# Generated by Django 3.0.7 on 2021-01-13 09:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('subject', models.CharField(default=None, max_length=500)),
                ('message', models.CharField(default=None, max_length=1000)),
                ('date_of_contact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=200)),
                ('pass_out', models.CharField(default=None, max_length=200)),
                ('stream', models.CharField(default=None, max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tap_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=None, max_length=500)),
                ('job_description', ckeditor.fields.RichTextField(default=None)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
