# Generated by Django 3.0.7 on 2021-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210113_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AlterField(
            model_name='register',
            name='stream',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MBA', 'MBA'), ('BE / Btech IT', 'BE / Btech IT'), ('BE / Btech Computer', 'BE / Btech Computer'), ('BE / Btech Mechanical', 'BE / Btech Mechanical'), ('BE / Btech Civil', 'BE / Btech Civil'), ('MSC', 'MSC'), ('BE / Btech Electrical', 'BE / Btech Electrical'), ('BCom', 'BCom'), ('BE / Btech Electronics', 'BE / Btech Electronics'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('Others', 'Others'), ('Career Counselling', 'Career Counselling')], default=None, max_length=100),
        ),
    ]
